FROM ubuntu:18.04
LABEL maintainer="minsoo Lee <minsoo.james1101@gmail.com>"
# insatll apache
RUN apt-get update && \
	apt-get install -y apache2
RUN echo "Test Web" > /var/www/html/index.html
EXPOSE 80
CMD ["/usr/sbin/apache2ctl", "-DFOREGROUND"]


